stages:
  - build
  - release

variables:
  ADDON_NAME: "Heracles"
  ZIP_FILE: "${ADDON_NAME}.zip"
  EXCLUDES: "--exclude=./${ADDON_NAME}/README.md --exclude=./${ADDON_NAME}/.git*"

build_addon:
  stage: build
  image: alpine:latest
  before_script:
    - apk add --no-cache zip
  script:
    - mkdir ../tmp/
    - cp -r ../$CI_PROJECT_NAME ../tmp/$ADDON_NAME
    - cd ../tmp/
    - zip -r "../$CI_PROJECT_NAME/$ZIP_FILE" . $EXCLUDES
  artifacts:
    paths:
      - ${ZIP_FILE}
  rules:
    - if: $CI_COMMIT_TAG

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Création de la release pour ${ADDON_NAME}"
  release:
    name: "Release $CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
    description: "Release générée automatiquement pour $ADDON_NAME"
    assets:
      links:
        - name: "${ZIP_FILE}"
          url: "${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_REF_NAME}/raw/${ZIP_FILE}?job=build_addon"
  rules:
    - if: $CI_COMMIT_TAG